magnum-infra_hosts:
  aio1:
    ip: 172.29.236.100
orchestration_hosts:
  aio1:
    ip: 172.29.236.100
swift-proxy_hosts:
  aio1:
    ip: 172.29.236.100
    container_vars:
      swift_proxy_vars:
        limit_container_types: swift_proxy
        read_affinity: "r1=100"
        write_affinity: "r1"
        write_affinity_node_count: "1 * replicas"
swift_hosts:
  aio1:
    ip: 172.29.236.100
    container_vars:
      swift_vars:
        limit_container_types: swift
        zone: 0
        region: 1
